# K-MEANS CLUSTERING

In [1]:
import cv2  
import numpy as np

# READING IMAGE

In [2]:
img=cv2.imread("tree.jpg")
img

array([[[ 81,  13,   0],
        [138,  57,  22],
        [185,  75,   9],
        ...,
        [111,  44,   0],
        [109,  44,   0],
        [109,  44,   0]],

       [[ 81,  13,   0],
        [138,  57,  22],
        [185,  75,   9],
        ...,
        [111,  44,   0],
        [109,  44,   0],
        [109,  44,   0]],

       [[ 81,  13,   0],
        [138,  57,  22],
        [185,  75,   9],
        ...,
        [111,  45,   0],
        [109,  44,   0],
        [109,  44,   0]],

       ...,

       [[  0,  11,   0],
        [ 15,  39,  27],
        [  0,  31,  17],
        ...,
        [  0, 115,  36],
        [  9, 125,  48],
        [ 15, 131,  54]],

       [[  0,  10,   0],
        [  9,  35,  22],
        [  3,  38,  24],
        ...,
        [  5, 130,  50],
        [  0, 127,  48],
        [  7, 137,  60]],

       [[  0,  12,   0],
        [  9,  35,  22],
        [  7,  43,  29],
        ...,
        [  4, 135,  54],
        [ 48, 183, 105],
        [ 46, 184, 106]]

# RGB CONVERSION

In [3]:
imgrgp=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# RESHAPE

In [4]:
vec=imgrgp.reshape((-1,3))
vec

array([[  0,  13,  81],
       [ 22,  57, 138],
       [  9,  75, 185],
       ...,
       [ 54, 135,   4],
       [105, 183,  48],
       [106, 184,  46]], dtype=uint8)

# float conversion

In [5]:
vec=np.float32(vec)
vec

array([[  0.,  13.,  81.],
       [ 22.,  57., 138.],
       [  9.,  75., 185.],
       ...,
       [ 54., 135.,   4.],
       [105., 183.,  48.],
       [106., 184.,  46.]], dtype=float32)

# Iteration Termination Criteria

In [6]:
criteria=(cv2.TERM_CRITERIA_EPS +cv2.TERM_CRITERIA_MAX_ITER,100,1)

In [7]:
criteria

(3, 100, 1)

# Cluster Conditions

In [8]:
k=3
attempts=100

# K-MEANS

In [9]:
compactness,label,center=cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)

In [10]:
compactness

13748184896.123161

In [11]:
label

array([[1],
       [2],
       [2],
       ...,
       [1],
       [1],
       [1]], dtype=int32)

In [12]:
center

array([[188.72441 , 179.41121 , 145.78102 ],
       [ 54.013527,  75.71114 ,  16.99485 ],
       [ 46.2994  , 105.88282 , 188.27603 ]], dtype=float32)

# UINT Conversion

In [13]:
center=np.uint8(center)
center

array([[188, 179, 145],
       [ 54,  75,  16],
       [ 46, 105, 188]], dtype=uint8)

# FLATTENING AND RESHAPE

In [14]:
res=center[label.flatten()]
res_img=res.reshape((imgrgp.shape))
res_img

array([[[ 54,  75,  16],
        [ 46, 105, 188],
        [ 46, 105, 188],
        ...,
        [ 46, 105, 188],
        [ 46, 105, 188],
        [ 46, 105, 188]],

       [[ 54,  75,  16],
        [ 46, 105, 188],
        [ 46, 105, 188],
        ...,
        [ 46, 105, 188],
        [ 46, 105, 188],
        [ 46, 105, 188]],

       [[ 54,  75,  16],
        [ 46, 105, 188],
        [ 46, 105, 188],
        ...,
        [ 46, 105, 188],
        [ 46, 105, 188],
        [ 46, 105, 188]],

       ...,

       [[ 54,  75,  16],
        [ 54,  75,  16],
        [ 54,  75,  16],
        ...,
        [ 54,  75,  16],
        [ 54,  75,  16],
        [ 54,  75,  16]],

       [[ 54,  75,  16],
        [ 54,  75,  16],
        [ 54,  75,  16],
        ...,
        [ 54,  75,  16],
        [ 54,  75,  16],
        [ 54,  75,  16]],

       [[ 54,  75,  16],
        [ 54,  75,  16],
        [ 54,  75,  16],
        ...,
        [ 54,  75,  16],
        [ 54,  75,  16],
        [ 54,  75,  16]]

# IMAGE

In [15]:
cv2.imshow('original',img)
cv2.imshow('segmented',res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
image=cv2.imread("tree.jpg")
segmented_images=cv2.pyrMeanShiftFiltering(image,40,40)
cv2.imshow('original_image',image)
cv2.imshow('segmented image',segmented_images)
cv2.waitKey(0)
cv2.destroyAllWindows()